// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/utils/utils.proto

package utils

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_STATUS_CODE_INVALID StatusCode = 0
	StatusCode_STATUS_CODE_OK      StatusCode = 1
)

var StatusCode_name = map[int32]string{
	0: "STATUS_CODE_INVALID",
	1: "STATUS_CODE_OK",
}

var StatusCode_value = map[string]int32{
	"STATUS_CODE_INVALID": 0,
	"STATUS_CODE_OK":      1,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be2a81d4b0ee8fc2, []int{0}
}

// 基本返回状态
type Status struct {
	// 状态码
	Code StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=utils.StatusCode" json:"code,omitempty"`
	// 返回信息
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_be2a81d4b0ee8fc2, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_STATUS_CODE_INVALID
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("utils.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*Status)(nil), "utils.Status")
}

func init() { proto.RegisterFile("src/utils/utils.proto", fileDescriptor_be2a81d4b0ee8fc2) }

var fileDescriptor_be2a81d4b0ee8fc2 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x2e, 0x4a, 0xd6,
	0x2f, 0x2d, 0xc9, 0xcc, 0x29, 0x86, 0x90, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60,
	0x8e, 0x92, 0x27, 0x17, 0x5b, 0x70, 0x49, 0x62, 0x49, 0x69, 0xb1, 0x90, 0x2a, 0x17, 0x4b, 0x72,
	0x7e, 0x4a, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x9f, 0x91, 0xa0, 0x1e, 0x44, 0x31, 0x44, 0xd2,
	0x39, 0x3f, 0x25, 0x35, 0x08, 0x2c, 0x2d, 0x24, 0xc1, 0xc5, 0x9e, 0x9b, 0x5a, 0x5c, 0x9c, 0x98,
	0x9e, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe3, 0x6a, 0x59, 0x72, 0x71, 0x21, 0x54,
	0x0b, 0x89, 0x73, 0x09, 0x07, 0x87, 0x38, 0x86, 0x84, 0x06, 0xc7, 0x3b, 0xfb, 0xbb, 0xb8, 0xc6,
	0x7b, 0xfa, 0x85, 0x39, 0xfa, 0x78, 0xba, 0x08, 0x30, 0x08, 0x09, 0x71, 0xf1, 0x21, 0x4b, 0xf8,
	0x7b, 0x0b, 0x30, 0x3a, 0xe9, 0x47, 0xe9, 0xa6, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7,
	0xe7, 0xea, 0x3b, 0x96, 0xa6, 0x97, 0x16, 0x97, 0x14, 0x59, 0x9a, 0xe9, 0x97, 0xe6, 0x65, 0xa6,
	0x65, 0xa6, 0xa6, 0x80, 0x5d, 0xac, 0x9f, 0x9e, 0x9f, 0x5f, 0x5a, 0x02, 0xf1, 0x43, 0x12, 0x1b,
	0x58, 0xc8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x48, 0x85, 0xd0, 0x51, 0xdd, 0x00, 0x00, 0x00,
}
